In [189]:
import torch
import numpy as np


torch.manual_seed(111)

### Task I
Create a random tensor 𝑇 of shape (4, 3, 5).

Compute:\
(1) the mean along the last dimension (shape: (4, 3));\
(2) the sum along the second dimension (shape: (4, 5));\
(3) the maximum value along the first dimension (shape: (3, 5)).

Reshape 𝑇 to a tensor of shape (6, 10) and back to (4, 3, 5)

In [190]:
# C H W
random_tensor = torch.rand((4, 3, 5))
random_tensor

tensor([[[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
         [0.6001, 0.9312, 0.2153, 0.6033, 0.7328],
         [0.1857, 0.5101, 0.7545, 0.2884, 0.5775]],

        [[0.0358, 0.1026, 0.3419, 0.4400, 0.6341],
         [0.6224, 0.6334, 0.8580, 0.1572, 0.7853],
         [0.1458, 0.4177, 0.3047, 0.0382, 0.5805]],

        [[0.2089, 0.3964, 0.3527, 0.5514, 0.3021],
         [0.8046, 0.9331, 0.2951, 0.5982, 0.6111],
         [0.2544, 0.0674, 0.1858, 0.2480, 0.6931]],

        [[0.7255, 0.6844, 0.2132, 0.7821, 0.0133],
         [0.3243, 0.9077, 0.8574, 0.1983, 0.0267],
         [0.9153, 0.2590, 0.2468, 0.9635, 0.7522]]])

In [191]:
x1 = torch.mean(random_tensor, dim=2)
x1.shape, x1

(torch.Size([4, 3]),
 tensor([[0.5601, 0.6165, 0.4632],
         [0.3109, 0.6113, 0.2973],
         [0.3623, 0.6484, 0.2897],
         [0.4837, 0.4629, 0.6274]]))

In [192]:
x2 = torch.sum(random_tensor, dim=1)
x2.shape, x2

(torch.Size([4, 5]),
 tensor([[1.5013, 2.3553, 1.2516, 1.1498, 1.9414],
         [0.8040, 1.1537, 1.5046, 0.6354, 1.9999],
         [1.2679, 1.3969, 0.8336, 1.3975, 1.6063],
         [1.9652, 1.8511, 1.3174, 1.9438, 0.7922]]))

In [193]:
# values, indices
x3, _ = torch.max(random_tensor, dim=0)
x3.shape, x3

(torch.Size([3, 5]),
 tensor([[0.7255, 0.9140, 0.3527, 0.7821, 0.6341],
         [0.8046, 0.9331, 0.8580, 0.6033, 0.7853],
         [0.9153, 0.5101, 0.7545, 0.9635, 0.7522]]))

In [194]:
random_tensor = random_tensor.reshape((6, 10))

random_tensor.shape

torch.Size([6, 10])

In [195]:
random_tensor = random_tensor.reshape((4, 3, 5))

random_tensor.shape

torch.Size([4, 3, 5])

### Task II

Create a batch of input vectors 𝑋 of shape (5, 3).\
Define learnable weights 𝑊 of shape (3,) and a bias 𝑏 (a scalar).\
Compute the output: 𝑦 = 𝑋𝑊^T + 𝑏 (what is its shape?).\
Define a target vector 𝑦 and a mean squared error loss: 𝐿 = mean((𝑦 − 𝑦_target)^2).\
Perform backpropagation to compute gradients.

In [196]:
X = torch.rand((5, 3))

W = torch.rand((3), requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

y = X @ W.T + b

y.shape

torch.Size([5])

In [197]:
y_true = torch.rand((y.shape))
y_true, y

(tensor([0.3294, 0.1775, 0.6404, 0.1907, 0.5397]),
 tensor([1.4017, 2.1990, 1.9885, 1.8275, 2.1410], grad_fn=<AddBackward0>))

In [198]:
def mean_squared_error(y_pred, y_true):
    return torch.mean((y_pred - y_true) ** 2)

In [199]:
L = mean_squared_error(y, y_true)
L

tensor(2.4595, grad_fn=<MeanBackward0>)

backpropagation

In [200]:
L.backward()

In [202]:
W.grad, b.grad

(tensor([1.5213, 1.9913, 1.4440]), tensor(3.0721))